export const FETCH_BEERS_REQUEST = 'FETCH_BEERS_REQUEST';
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';
export const FETCH_BEERS_SUCCESS_EMPTY = 'FETCH_BEERS_SUCCESS_EMPTY';
export const FETCH_BEERS_FAILURE = 'FETCH_BEERS_FAILURE';
export const FETCH_BEERS_NEXT_PAGE = 'FETCH_BEERS_NEXT_PAGE';
export const FETCH_BEERS_PREV_PAGE = 'FETCH_BEERS_PREV_PAGE';
