export const SERVICE_URL = 'https://api.punkapi.com/v2/beers';
export const FETCH_BEERS_REQUEST = 'FETCH_BEERS_REQUEST';
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';
export const FETCH_BEERS_SUCCESS_EMPTY = 'FETCH_BEERS_SUCCESS_EMPTY';
export const FETCH_BEERS_FAILURE = 'FETCH_BEERS_FAILURE';